#Faça um programa que exiba a seguinte receita de bolo de chocolate. Exiba um item por vez:

print("INGREDIENTES PARA UMA RECEITA DE BOLO\n")
print("2 xícaras de farinha de trigo")
input()
print("1 xícaras de açucar")
input()
print("2 xícaras de cacau em pó")
input()
print("1 colher de chá de bicarbonato de sódio")
input()
print("1 colher de chá de fermento em pó")
input()
print("1/2 colher de chá sal")
input()
print("2 ovos")
input()
print("1 xícara de leite")
input()
print("1/2 xícara de oleo vegetal")
input()
print("2 colheres de chá de extrato de baunilha")
input()